name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller Pillow

    - name: Install ImageMagick (macOS only)
      if: runner.os == 'macOS'
      run: brew install imagemagick

    - name: Create .icns file (macOS only)
      if: runner.os == 'macOS'
      run: magick "ffmpeg-Audio-Converter.png" -resize 256x256 -define icon:auto-resize=256,128,64,48,32,16 app_icon.icns

    - name: Run PyInstaller on Windows
      if: runner.os == 'Windows'
      run: python -m PyInstaller --noconfirm --onefile --windowed --icon="app_icon.ico" --add-data="app_icon.ico;." main.py

    - name: Install Inno Setup (Windows only)
      if: runner.os == 'Windows'
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
      with:
        path: setup.iss

    - name: Run PyInstaller on macOS
      if: runner.os == 'macOS'
      run: python -m PyInstaller --noconfirm --windowed --icon="app_icon.icns" --add-data="app_icon.ico:." main.py

    - name: Run PyInstaller on Linux
      if: runner.os == 'Linux'
      run: python -m PyInstaller --noconfirm --onefile --name="ffmpeg-audio-converter-Linux" main.py

    - name: Prepare Windows Artifacts
      if: runner.os == 'Windows'
      run: |
        mv dist/main.exe dist/ffmpeg-audio-converter-Windows-Portable.exe
        mv dist/ffmpeg_Audio_Converter_setup.exe dist/ffmpeg-audio-converter-Windows-Installer.exe
    
    - name: Prepare macOS Artifact
      if: runner.os == 'macOS'
      run: zip -r ffmpeg-audio-converter-macOS.zip dist/main.app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.os }}
        path: |
          dist/ffmpeg-audio-converter-Windows-Portable.exe
          dist/ffmpeg-audio-converter-Windows-Installer.exe
          ffmpeg-audio-converter-macOS.zip
          dist/ffmpeg-audio-converter-Linux
        if-no-files-found: ignore

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      
      - name: List downloaded files
        run: ls -R artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/build-artifacts-windows-latest/ffmpeg-audio-converter-Windows-Portable.exe
            artifacts/build-artifacts-windows-latest/ffmpeg-audio-converter-Windows-Installer.exe
            artifacts/build-artifacts-macos-latest/ffmpeg-audio-converter-macOS.zip
            artifacts/build-artifacts-ubuntu-latest/ffmpeg-audio-converter-Linux
          body: "Automated release for ${{ github.ref_name }}"
          draft: true
